Repository mhvk/baseband-tasks, pull requests merged in 2018-11, with the labels that each got.

#34 Small breakages
  docs/helpers/fourier.rst
  setup.cfg
Labels: testing

#33 Refactor
  scintillometry/base.py
  scintillometry/channelize.py
  scintillometry/functions.py
  scintillometry/generators.py
  scintillometry/tests/test_base.py
  scintillometry/tests/test_channelize.py
  scintillometry/tests/test_functions.py
  scintillometry/tests/test_generators.py
  scintillometry/tests/test_simulate.py
Labels: refactoring

#36 Set up a default fft maker.
  scintillometry/channelize.py
  scintillometry/fourier/__init__.py
  scintillometry/fourier/base.py
  scintillometry/fourier/tests/test_fourier.py
  scintillometry/tests/test_channelize.py
Labels: bug, enhancement, fourier

#39 Try using conda depencency of pyfftw
  .travis.yml
Labels: testing

#41 Prevent pytest from picking up test function as a test
  scintillometry/_astropy_init.py
Labels: testing

#42 Add a Power task, which squares while keeping polarization cross-products
  scintillometry/base.py
  scintillometry/functions.py
  scintillometry/tests/test_functions.py
Labels: enhancement, functions

#44 Very simple implementation of a BaseData class with count attribute.
  scintillometry/base.py
  scintillometry/tests/test_basedata.py
Labels: Work in progress, enhancement

#43 Sample Shape changes, e.g., to ensure pol/freq etc are on separate axes.
  docs/index.rst
  docs/tasks/dispersion.rst
  docs/tasks/shaping.rst
  scintillometry/base.py
  scintillometry/shaping.py
  scintillometry/tests/test_base.py
  scintillometry/tests/test_shaping.py
Labels: enhancement, shaping
